"""
CPV Code Classifier
-------------------
Predicts EU CPV (Common Procurement Vocabulary) codes for a tender description,
aggregated to the 4-digit division level.

Design principles:
- ZERO HALLUCINATION: predictions are ranked from the official CPV CSV only.
  No code is ever generated by a language model. The classifier is pure
  cosine similarity over a multilingual sentence-transformer embedding space.
- DETERMINISTIC: same input -> same output, every time.
- LANGUAGE-NATIVE: each tender is matched only against CPV descriptions in
  the same language (auto-detected, user-overridable). This eliminates
  cross-language noise and sharpens precision.
"""
from __future__ import annotations

import io
import re
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

from stopwords import get_stopwords

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="CPV Classifier",
    page_icon="🇪🇺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DATA_DIR = Path(__file__).parent / "data"
CPV_CSV = DATA_DIR / "cpv_full.csv"
EMBEDDINGS_FILE = DATA_DIR / "cpv_embeddings.npz"
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

# Map our 2-letter CPV column codes to (display_name, lingua Language enum name).
# Lingua enum names are kept as strings so we can resolve them lazily.
LANG_INFO: dict[str, tuple[str, str]] = {
    "BG": ("Bulgarian",  "BULGARIAN"),
    "CS": ("Czech",      "CZECH"),
    "DA": ("Danish",     "DANISH"),
    "DE": ("German",     "GERMAN"),
    "EL": ("Greek",      "GREEK"),
    "EN": ("English",    "ENGLISH"),
    "ES": ("Spanish",    "SPANISH"),
    "ET": ("Estonian",   "ESTONIAN"),
    "FI": ("Finnish",    "FINNISH"),
    "FR": ("French",     "FRENCH"),
    "GA": ("Irish",      "IRISH"),
    "HR": ("Croatian",   "CROATIAN"),
    "HU": ("Hungarian",  "HUNGARIAN"),
    "IT": ("Italian",    "ITALIAN"),
    "LT": ("Lithuanian", "LITHUANIAN"),
    "LV": ("Latvian",    "LATVIAN"),
    "MT": ("Maltese",    "MALTESE"),
    "NL": ("Dutch",      "DUTCH"),
    "PL": ("Polish",     "POLISH"),
    "PT": ("Portuguese", "PORTUGUESE"),
    "RO": ("Romanian",   "ROMANIAN"),
    "SK": ("Slovak",     "SLOVAK"),
    "SL": ("Slovene",    "SLOVENE"),
    "SV": ("Swedish",    "SWEDISH"),
}
LANG_COLUMNS = list(LANG_INFO.keys())
LINGUA_TO_CPV: dict[str, str] = {info[1]: code for code, info in LANG_INFO.items()}


# ---------------------------------------------------------------------------
# Cached loaders
# ---------------------------------------------------------------------------
@st.cache_data(show_spinner="Loading CPV catalogue…")
def load_cpv_catalogue() -> pd.DataFrame:
    """Load the official CPV catalogue and add helper columns."""
    df = pd.read_csv(CPV_CSV, encoding="utf-8-sig", dtype=str).fillna("")
    df["code_clean"] = df["CODE"].str.split("-").str[0]
    df["div4"] = df["code_clean"].str[:4] + "0000"
    return df


@st.cache_data(show_spinner="Loading precomputed embeddings…")
def load_embeddings() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load the precomputed embedding matrix and parallel code/lang arrays."""
    data = np.load(EMBEDDINGS_FILE, allow_pickle=False)
    return data["matrix"].astype(np.float32), data["codes"], data["langs"]


@st.cache_data(show_spinner="Building per-language indexes…")
def build_language_indexes(
    _matrix: np.ndarray,  # leading underscore -> not part of cache key
    _codes: np.ndarray,
    _langs: np.ndarray,
) -> dict[str, dict]:
    """
    Pre-slice the embedding matrix into one bank per language so query-time
    cosine similarity only touches rows for the selected language. With ~9.5k
    rows per language vs. ~227k rows total, queries are ~24x faster.
    """
    indexes: dict[str, dict] = {}
    for lang in LANG_COLUMNS:
        mask = _langs == lang
        if not mask.any():
            continue
        indexes[lang] = {
            "matrix": _matrix[mask],
            "codes": _codes[mask],
        }
    return indexes


# ---------------------------------------------------------------------------
# BM25 keyword index (per language)
# ---------------------------------------------------------------------------
# Tokenizer: lowercase + Unicode word boundaries. We keep digits because
# CPV descriptions sometimes contain numeric tokens that are meaningful
# (e.g. "Class 2 medical devices"). Stopwords are filtered per language.
TOKEN_RE = re.compile(r"\w+", flags=re.UNICODE)


def tokenize(text: str, lang: str) -> list[str]:
    """Lowercase + word-tokenize + strip stopwords for the given language."""
    if not text:
        return []
    stops = get_stopwords(lang)
    return [
        t for t in TOKEN_RE.findall(text.lower())
        if len(t) > 1 and t not in stops
    ]


@st.cache_resource(show_spinner="Building BM25 keyword indexes…")
def build_bm25_indexes(_catalogue: pd.DataFrame) -> dict[str, dict]:
    """
    Build one BM25 index per language. Each index is parallel to the
    catalogue rows (one document per CPV code = the description in that
    language). Returns a dict mapping language code to:
        bm25  : a BM25Okapi instance
        codes : array of CPV codes parallel to the BM25 corpus
    """
    from rank_bm25 import BM25Okapi
    indexes: dict[str, dict] = {}
    for lang in LANG_COLUMNS:
        if lang not in _catalogue.columns:
            continue
        docs = _catalogue[lang].fillna("").tolist()
        codes = _catalogue["code_clean"].tolist()
        # Drop rows with empty descriptions in this language
        pairs = [(c, d) for c, d in zip(codes, docs) if d.strip()]
        if not pairs:
            continue
        kept_codes = [c for c, _ in pairs]
        tokenized = [tokenize(d, lang) for _, d in pairs]
        # rank_bm25 fails on empty docs, so substitute a single dummy token
        tokenized = [t if t else ["_"] for t in tokenized]
        indexes[lang] = {
            "bm25": BM25Okapi(tokenized),
            "codes": np.array(kept_codes),
        }
    return indexes


def normalize_scores(scores: np.ndarray) -> np.ndarray:
    """Min-max normalize to [0, 1]. Returns zeros if all scores are equal."""
    if scores.size == 0:
        return scores
    lo, hi = float(scores.min()), float(scores.max())
    if hi - lo < 1e-9:
        return np.zeros_like(scores, dtype=np.float32)
    return ((scores - lo) / (hi - lo)).astype(np.float32)


@st.cache_resource(show_spinner="Loading multilingual embedding model…")
def load_model():
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer(MODEL_NAME)


@st.cache_resource(show_spinner="Loading language detector…")
def load_language_detector():
    """
    Build a lingua detector restricted to the EU languages it supports.

    Lingua covers 23 of the 24 official EU languages — Maltese is not in
    its language model. We build the detector from whichever enum members
    actually exist, so a Maltese tender simply won't auto-detect (the user
    can still pick Maltese manually from the override dropdown). The
    ``unsupported`` set is exposed so the UI can mention it where helpful.
    """
    from lingua import Language, LanguageDetectorBuilder
    languages = []
    unsupported: list[str] = []
    for cpv_code, (display_name, lingua_name) in LANG_INFO.items():
        member = getattr(Language, lingua_name, None)
        if member is None:
            unsupported.append(cpv_code)
            continue
        languages.append(member)
    detector = LanguageDetectorBuilder.from_languages(*languages).build()
    return detector, set(unsupported)


# ---------------------------------------------------------------------------
# Language detection
# ---------------------------------------------------------------------------
def detect_language(detector, text: str) -> tuple[str | None, float]:
    """
    Detect the language of ``text``.

    Returns
    -------
    (cpv_lang_code, confidence) where cpv_lang_code is one of LANG_COLUMNS
    (e.g. 'EL', 'EN') or None if detection failed. Confidence is in [0, 1].
    """
    if not text or len(text.strip()) < 3:
        return None, 0.0
    try:
        results = detector.compute_language_confidence_values(text)
    except Exception:
        return None, 0.0
    if not results:
        return None, 0.0
    top = results[0]
    cpv_code = LINGUA_TO_CPV.get(top.language.name)
    return cpv_code, float(top.value)


# ---------------------------------------------------------------------------
# Classification (single-language)
# ---------------------------------------------------------------------------
def embed_query(model, text: str) -> np.ndarray:
    vec = model.encode([text], normalize_embeddings=True, show_progress_bar=False)
    return vec.astype(np.float32)[0]


def classify(
    text: str,
    lang: str,
    model,
    indexes: dict[str, dict],
    bm25_indexes: dict[str, dict],
    catalogue: pd.DataFrame,
    threshold: float,
    alpha: float = 0.75,
) -> pd.DataFrame:
    """
    Hybrid score = α·cosine + (1-α)·BM25, both normalized to [0, 1] within
    the chosen language. Then roll up to 4-digit division. Returns one row
    per div4 above ``threshold``, sorted by descending score, with descriptions
    in ``lang``.

    ``alpha`` controls the embedding/keyword balance:
       1.0 = pure embeddings (semantic), 0.0 = pure BM25 (keyword), 0.6 default.

    Codes mentioned literally in the source text get a fixed 0.95 score and
    bypass the threshold entirely (same behaviour as before).
    """
    if lang not in indexes:
        return pd.DataFrame()

    # ---- Step 1: explicit codes from the source ----
    extracted = extract_cpv_codes(text, catalogue)

    code_to_desc = dict(zip(catalogue["code_clean"], catalogue[lang]))
    div_only = catalogue[catalogue["code_clean"] == catalogue["div4"]]
    div_to_desc = dict(zip(div_only["div4"], div_only[lang]))

    extracted_rows = []
    extracted_div4s: set[str] = set()
    for item in extracted:
        extracted_rows.append({
            "div4": item["div4"],
            "division_description": div_to_desc.get(item["div4"], ""),
            "score": 0.95,
            "cosine": np.nan,
            "bm25": np.nan,
            "top_code": item["raw"],
            "top_code_description": code_to_desc.get(item["code_8"], ""),
            "source": "📄 In document",
        })
        extracted_div4s.add(item["div4"])

    # ---- Step 2a: embedding (cosine) scores ----
    bank = indexes[lang]
    qv = embed_query(model, text)
    cos_sims = bank["matrix"] @ qv  # cosine sim, both sides L2-normalised

    cos_df = pd.DataFrame({"code": bank["codes"], "cosine_raw": cos_sims})
    cos_df = cos_df.loc[cos_df.groupby("code")["cosine_raw"].idxmax()].reset_index(drop=True)

    # ---- Step 2b: BM25 keyword scores ----
    if lang in bm25_indexes:
        bm25_bank = bm25_indexes[lang]
        query_tokens = tokenize(text, lang)
        if query_tokens:
            bm_raw = np.asarray(bm25_bank["bm25"].get_scores(query_tokens), dtype=np.float32)
        else:
            bm_raw = np.zeros(len(bm25_bank["codes"]), dtype=np.float32)
        bm_df = pd.DataFrame({"code": bm25_bank["codes"], "bm25_raw": bm_raw})
        bm_df = bm_df.loc[bm_df.groupby("code")["bm25_raw"].idxmax()].reset_index(drop=True)
    else:
        bm_df = pd.DataFrame({"code": cos_df["code"], "bm25_raw": 0.0})

    # ---- Step 2c: merge and fuse ----
    df = cos_df.merge(bm_df, on="code", how="left").fillna({"bm25_raw": 0.0})
    df["cosine"] = normalize_scores(df["cosine_raw"].to_numpy())
    df["bm25"] = normalize_scores(df["bm25_raw"].to_numpy())
    df["score"] = (alpha * df["cosine"] + (1 - alpha) * df["bm25"]).astype(np.float32)

    code_to_div = dict(zip(catalogue["code_clean"], catalogue["div4"]))
    df["div4"] = df["code"].map(code_to_div)
    df = df.dropna(subset=["div4"])

    # Roll up to div4: keep the strongest descendant per division
    idx = df.groupby("div4")["score"].idxmax()
    rolled = df.loc[idx].reset_index(drop=True).rename(columns={"code": "top_code"})
    rolled["division_description"] = rolled["div4"].map(div_to_desc).fillna("")
    rolled["top_code_description"] = rolled["top_code"].map(code_to_desc).fillna("")
    rolled["source"] = "🔍 Semantic + keyword"

    rolled = rolled[rolled["score"] >= threshold]
    rolled = rolled[~rolled["div4"].isin(extracted_div4s)]

    # ---- Step 3: combine and order ----
    columns = ["div4", "division_description", "score", "cosine", "bm25",
               "top_code", "top_code_description", "source"]
    if extracted_rows:
        combined = pd.concat(
            [pd.DataFrame(extracted_rows, columns=columns), rolled[columns]],
            ignore_index=True,
        )
    else:
        combined = rolled[columns].reset_index(drop=True)

    combined = combined.sort_values("score", ascending=False).reset_index(drop=True)
    return combined


# ---------------------------------------------------------------------------
# File extraction
# ---------------------------------------------------------------------------
def extract_text_from_upload(uploaded_file) -> str:
    name = uploaded_file.name.lower()
    raw = uploaded_file.read()

    if name.endswith(".txt") or name.endswith(".md"):
        for enc in ("utf-8", "utf-8-sig", "cp1253", "latin-1"):
            try:
                return raw.decode(enc)
            except UnicodeDecodeError:
                continue
        return raw.decode("utf-8", errors="replace")

    if name.endswith(".pdf"):
        try:
            from pypdf import PdfReader
            reader = PdfReader(io.BytesIO(raw))
            return "\n".join((p.extract_text() or "") for p in reader.pages)
        except Exception as e:
            st.error(f"Could not parse PDF: {e}")
            return ""

    if name.endswith(".docx"):
        try:
            from docx import Document
            doc = Document(io.BytesIO(raw))
            parts = [p.text for p in doc.paragraphs]
            for table in doc.tables:
                for row in table.rows:
                    parts.extend(cell.text for cell in row.cells)
            return "\n".join(parts)
        except Exception as e:
            st.error(f"Could not parse DOCX: {e}")
            return ""

    if name.endswith(".xlsx") or name.endswith(".xls"):
        try:
            xl = pd.ExcelFile(io.BytesIO(raw))
            chunks = []
            for sheet in xl.sheet_names:
                s = xl.parse(sheet, dtype=str).fillna("")
                chunks.append(f"# Sheet: {sheet}\n" + s.to_csv(index=False))
            return "\n\n".join(chunks)
        except Exception as e:
            st.error(f"Could not parse spreadsheet: {e}")
            return ""

    st.warning(f"Unsupported file type: {name}")
    return ""


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


# ---------------------------------------------------------------------------
# Explicit CPV code extraction
# ---------------------------------------------------------------------------
# Match an 8-digit CPV code, optionally followed by '-' and a check digit.
# We anchor with non-digit boundaries so we don't pick up digits in the
# middle of longer numbers (invoice IDs, dates run together, etc.).
CPV_PATTERN = re.compile(r"(?<!\d)(\d{8})(?:-(\d))?(?!\d)")


def extract_cpv_codes(text: str, catalogue: pd.DataFrame) -> list[dict]:
    """
    Find CPV-shaped tokens in ``text`` and validate them against the official
    catalogue. Returns a list of dicts in the order found, each with:

        raw          : the exact substring as it appeared in the source
        code_8       : 8-digit code (no check digit)
        code_full    : 8-digit code with check digit, e.g. '45213316-1'
        div4         : the 4-digit division, e.g. '45210000'
        position     : character offset in the cleaned text (for stable order)

    Codes that look CPV-shaped but don't exist in the catalogue are dropped
    silently — this is the no-hallucination guarantee extended to extraction.
    Duplicates are removed (same code_full appearing twice keeps the first).
    """
    if not text:
        return []

    valid_codes: set[str] = set(catalogue["code_clean"])
    code_to_full: dict[str, str] = dict(zip(catalogue["code_clean"], catalogue["CODE"]))
    code_to_div: dict[str, str] = dict(zip(catalogue["code_clean"], catalogue["div4"]))

    seen: set[str] = set()
    found: list[dict] = []
    for m in CPV_PATTERN.finditer(text):
        code_8 = m.group(1)
        if code_8 not in valid_codes:
            continue  # CPV-shaped but not a real code — drop silently
        if code_8 in seen:
            continue
        seen.add(code_8)
        found.append({
            "raw": m.group(0),
            "code_8": code_8,
            "code_full": code_to_full.get(code_8, code_8),
            "div4": code_to_div[code_8],
            "position": m.start(),
        })
    return found


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------
def language_label(code: str) -> str:
    return f"{LANG_INFO[code][0]} ({code})"


def render_sidebar() -> dict:
    st.sidebar.header("⚙️ Settings")
    threshold = st.sidebar.slider(
        "Confidence threshold",
        min_value=0.20, max_value=0.90, value=0.75, step=0.01,
        help=(
            "Minimum hybrid score (0–1) for a CPV division to be returned. "
            "Lower = more recall. Higher = more precision. "
            "Sweet spot: 0.40–0.55."
        ),
    )
    alpha = st.sidebar.slider(
        "Semantic vs. keyword balance (α)",
        min_value=0.0, max_value=1.0, value=0.75, step=0.05,
        help=(
            "Weight given to embedding (semantic) similarity vs. BM25 (keyword) "
            "matching: score = α·semantic + (1−α)·keyword. "
            "1.0 = pure semantic (catches paraphrases). "
            "0.0 = pure keyword (catches verbatim catalogue terms). "
            "0.6 (default) handles both well in most cases."
        ),
    )
    max_results = st.sidebar.number_input(
        "Maximum codes to display",
        min_value=1, max_value=100, value=15, step=1,
        help="Hard cap on the number of rows shown, after the threshold filter.",
    )
    st.sidebar.divider()
    st.sidebar.markdown(
        "**Model**\n\n"
        "`paraphrase-multilingual-mpnet-base-v2` (semantic) + BM25 (keyword)\n\n"
        "Each tender is matched only against CPV descriptions in the **same "
        "language**. **No LLM is used in classification — codes cannot be "
        "hallucinated.**"
    )
    return {
        "threshold": threshold,
        "alpha": alpha,
        "max_results": int(max_results),
    }


def render_results(results: pd.DataFrame, max_results: int, lang: str) -> None:
    if results.empty:
        st.warning(
            "No CPV codes scored above the threshold. "
            "Try lowering the threshold in the sidebar, or provide more descriptive text."
        )
        return

    n_extracted = int((results["source"] == "📄 In document").sum())
    n_semantic = len(results) - n_extracted

    shown = results.head(max_results).copy()
    shown["score"] = shown["score"].round(4)
    shown["cosine"] = shown["cosine"].round(3)
    shown["bm25"] = shown["bm25"].round(3)
    shown.insert(0, "rank", range(1, len(shown) + 1))
    lang_name = LANG_INFO[lang][0]
    shown = shown.rename(
        columns={
            "div4": "CPV (4-digit)",
            "division_description": f"Division ({lang_name})",
            "score": "Confidence",
            "cosine": "Semantic",
            "bm25": "Keyword",
            "top_code": "Best matching subcode",
            "top_code_description": f"Subcode ({lang_name})",
            "source": "Source",
        }
    )

    # Build the success message
    if n_extracted and n_semantic:
        msg = (
            f"Found **{n_extracted}** explicit CPV code(s) in the document and "
            f"**{n_semantic}** additional semantic match(es) above threshold "
            f"({lang_name})."
        )
    elif n_extracted:
        msg = (
            f"Found **{n_extracted}** explicit CPV code(s) in the document. "
            f"No additional semantic matches passed the threshold."
        )
    else:
        msg = (
            f"Found **{n_semantic}** semantic CPV match(es) above threshold "
            f"({lang_name}). Showing top {len(shown)}."
        )
    st.success(msg)

    # Highlight rows that came from explicit extraction
    def highlight_extracted(row):
        if row["Source"] == "📄 In document":
            # Soft amber background + slightly bolder text
            return ["background-color: #FEF3C7; font-weight: 600"] * len(row)
        return [""] * len(row)

    styled = shown.style.apply(highlight_extracted, axis=1)
    st.dataframe(
        styled,
        hide_index=True,
        use_container_width=True,
        column_config={
            "Confidence": st.column_config.ProgressColumn(
                "Confidence", min_value=0.0, max_value=1.0, format="%.3f",
            ),
        },
    )

    if n_extracted:
        st.caption(
            "📄 Highlighted rows are CPV codes that appeared **literally** in the "
            "source text/file and were validated against the official catalogue. "
            "They are shown with fixed confidence 0.95 and bypass the threshold."
        )

    csv = shown.to_csv(index=False).encode("utf-8")
    st.download_button(
        "⬇️ Download results as CSV",
        data=csv,
        file_name=f"cpv_predictions_{lang}.csv",
        mime="text/csv",
    )


def language_picker(text: str, detector, unsupported_detect: set[str]) -> str | None:
    """Render the auto-detect + override widget. Returns the chosen CPV lang code."""
    if not text:
        st.info("Enter some text or upload a file to detect the language.")
        return None

    detected, confidence = detect_language(detector, text)

    col1, col2 = st.columns([3, 2])
    with col1:
        default_index = (
            LANG_COLUMNS.index(detected) if detected in LANG_COLUMNS
            else LANG_COLUMNS.index("EN")
        )
        chosen = st.selectbox(
            "Language for CPV matching",
            options=LANG_COLUMNS,
            index=default_index,
            format_func=language_label,
            help=(
                "Auto-detected from your text. The CPV catalogue will be "
                "searched in this language and results will be shown in it. "
                "Override if the detection is wrong."
            ),
            key="lang_choice",
        )
    with col2:
        if detected:
            label = LANG_INFO[detected][0]
            if confidence >= 0.85:
                st.success(f"Detected: **{label}** ({confidence:.0%})")
            elif confidence >= 0.50:
                st.info(f"Detected: **{label}** ({confidence:.0%}) — please verify")
            else:
                st.warning(
                    f"Low-confidence detection: **{label}** ({confidence:.0%}). "
                    "Please confirm or override."
                )
        else:
            st.warning("Could not detect language — please pick one manually.")

    if detected is not None and chosen != detected:
        st.caption(
            f"⚠️ You overrode auto-detection ({LANG_INFO[detected][0]} → "
            f"{LANG_INFO[chosen][0]}). Matching will use **{LANG_INFO[chosen][0]}**."
        )

    if chosen in unsupported_detect:
        st.caption(
            f"ℹ️ {LANG_INFO[chosen][0]} is not supported by the auto-detector, "
            "but CPV matching against it works normally."
        )
    return chosen


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    st.title("🇪🇺 CPV Code Classifier")
    st.caption(
        "Predicts EU **Common Procurement Vocabulary** codes for a tender, aggregated "
        "to the 4-digit division level. Language-native, deterministic, hallucination-free."
    )

    settings = render_sidebar()

    catalogue = load_cpv_catalogue()
    matrix, codes, langs = load_embeddings()
    indexes = build_language_indexes(matrix, codes, langs)
    bm25_indexes = build_bm25_indexes(catalogue)
    model = load_model()
    detector, unsupported_detect = load_language_detector()

    tab_text, tab_file = st.tabs(["📝 Paste text", "📎 Upload file"])
    text_to_classify = ""

    with tab_text:
        text_to_classify = st.text_area(
            "Tender description",
            height=260,
            placeholder="Paste the tender title, scope, or full description in any EU language…",
        )

    with tab_file:
        uploaded = st.file_uploader(
            "Upload a tender document",
            type=["txt", "md", "pdf", "docx", "xlsx", "xls"],
            help="Text is extracted locally; nothing is sent to any external service.",
        )
        if uploaded is not None:
            extracted = extract_text_from_upload(uploaded)
            if extracted:
                with st.expander("Preview extracted text", expanded=False):
                    st.text(extracted[:4000] + ("…" if len(extracted) > 4000 else ""))
                text_to_classify = extracted

    text_to_classify = clean_text(text_to_classify)

    st.divider()
    chosen_lang = language_picker(text_to_classify, detector, unsupported_detect)

    classify_btn = st.button(
        "🔍 Classify",
        type="primary",
        disabled=not (text_to_classify and chosen_lang),
    )

    if classify_btn and text_to_classify and chosen_lang:
        with st.spinner(
            f"Embedding and ranking against {LANG_INFO[chosen_lang][0]} CPV descriptions…"
        ):
            results = classify(
                text=text_to_classify,
                lang=chosen_lang,
                model=model,
                indexes=indexes,
                bm25_indexes=bm25_indexes,
                catalogue=catalogue,
                threshold=settings["threshold"],
                alpha=settings["alpha"],
            )
        render_results(results, settings["max_results"], chosen_lang)


if __name__ == "__main__":
    main()
